import type { Dashboard } from './types';

const fixtureNow = new Date();
const isoOffset = (minutes: number): string =>
  new Date(fixtureNow.getTime() + minutes * 60_000).toISOString();
const dateOffset = (days: number): string =>
  new Date(fixtureNow.getTime() + days * 86_400_000).toISOString().slice(0, 10);
const fixtureObservedAt = isoOffset(0);
const fixtureResetAt = isoOffset(120);

export const fixtureDashboard: Dashboard = {
  demoMode: true,
  collectorState: 'fixture data loaded',
  codexVersion: '0.144.1',
  lastEventAt: fixtureObservedAt,
  quota: [
    {
      id: 'codex:primary',
      name: 'Codex',
      windowLabel: '5 hour window',
      usedPercent: 82,
      remainingPercent: 18,
      resetsAt: fixtureResetAt,
      accuracy: 'reported_exact',
    },
    {
      id: 'codex:secondary',
      name: 'Codex',
      windowLabel: 'Weekly window',
      usedPercent: 41,
      remainingPercent: 59,
      resetsAt: '2026-07-27T00:00:00Z',
      accuracy: 'reported_exact',
    },
  ],
  quotaStatus: {
    state: 'fixture',
    accuracy: 'reported_exact',
    source: 'Synthetic App Server fixture',
    lastObservedAt: '2026-07-22T12:42:00Z',
    reason: null,
    requiredIntegration: 'Read-only App Server collection',
  },
  forecasts: [
    {
      bucketId: 'codex:primary',
      bucketName: 'Codex',
      windowLabel: '5 hour window',
      generatedAt: fixtureObservedAt,
      resetsAt: fixtureResetAt,
      currentUsedPercent: 82,
      remainingPercent: 18,
      latestIntervalRatePph: 10,
      rolling30mRatePph: 10,
      rolling1hRatePph: 10,
      rolling3hRatePph: null,
      rolling6hRatePph: null,
      completeWindowRatePph: 10,
      ewmaRatePph: 9.7,
      regressionRatePph: 10,
      selectedRatePph: 10,
      safeRatePph: 9,
      paceRatio: 1.11,
      risk: 'at_risk',
      predictedExhaustionAt: isoOffset(108),
      projectedUsageAtReset: 102,
      exhaustionBeforeReset: true,
      quality: {
        selectedModel: 'ordinary_least_squares',
        confidence: 'medium',
        observationCount: 5,
        coverageDurationMinutes: 120,
        pollingRegularity: 1,
        largestGapMinutes: 30,
        modelAgreement: 0.97,
        slopeStability: 0.94,
        invalidationReason: null,
        missingSignals: [],
      },
      trajectory: [
        {
          observedAt: isoOffset(-120),
          reportedUsedPercent: 62,
          rollingTrendPercent: null,
          forecastUsedPercent: null,
          confidenceLowPercent: null,
          confidenceHighPercent: null,
        },
        {
          observedAt: isoOffset(-90),
          reportedUsedPercent: 67,
          rollingTrendPercent: null,
          forecastUsedPercent: null,
          confidenceLowPercent: null,
          confidenceHighPercent: null,
        },
        {
          observedAt: isoOffset(-60),
          reportedUsedPercent: 72,
          rollingTrendPercent: 72,
          forecastUsedPercent: null,
          confidenceLowPercent: null,
          confidenceHighPercent: null,
        },
        {
          observedAt: isoOffset(-30),
          reportedUsedPercent: 77,
          rollingTrendPercent: 77,
          forecastUsedPercent: null,
          confidenceLowPercent: null,
          confidenceHighPercent: null,
        },
        {
          observedAt: fixtureObservedAt,
          reportedUsedPercent: 82,
          rollingTrendPercent: 82,
          forecastUsedPercent: 82,
          confidenceLowPercent: 82,
          confidenceHighPercent: 82,
        },
        {
          observedAt: isoOffset(60),
          reportedUsedPercent: null,
          rollingTrendPercent: null,
          forecastUsedPercent: 92,
          confidenceLowPercent: 89,
          confidenceHighPercent: 95,
        },
        {
          observedAt: fixtureResetAt,
          reportedUsedPercent: null,
          rollingTrendPercent: null,
          forecastUsedPercent: 102,
          confidenceLowPercent: 96,
          confidenceHighPercent: 108,
        },
      ],
      burnRates: [-120, -90, -60, -30, 0].map((minutes, index) => ({
        observedAt: isoOffset(minutes),
        intervalRatePph: index === 0 ? null : 10,
        rolling30mRatePph: index === 0 ? null : 10,
        rolling1hRatePph: index < 2 ? null : 10,
        rolling3hRatePph: null,
        rolling6hRatePph: null,
        ewmaRatePph: index === 0 ? null : 9.7,
        safeRatePph: 9,
      })),
      status: {
        state: 'fixture',
        accuracy: 'estimated',
        source: 'Synthetic local forecast',
        lastObservedAt: fixtureObservedAt,
        reason: null,
        requiredIntegration: 'Read-only App Server quota history',
      },
    },
  ],
  forecastStatus: {
    state: 'fixture',
    accuracy: 'estimated',
    source: 'Synthetic local forecast',
    lastObservedAt: fixtureObservedAt,
    reason: null,
    requiredIntegration: 'Read-only App Server quota history',
  },
  accountUsage: {
    observedAt: '2026-07-22T12:42:00Z',
    lifetimeTokens: 25_480_000,
    peakDailyTokens: 3_420_000,
    longestRunningTurnSec: 10_860,
    currentStreakDays: 4,
    longestStreakDays: 11,
    dailyUsageBuckets: [
      1_284_000, 2_946_000, 1_672_000, 3_420_000, 2_138_200, 2_584_000, 1_954_000,
    ].map((tokens, index) => ({
      startDate: dateOffset(index - 6),
      tokens,
      observedAt: isoOffset((index - 6) * 1_440),
      accuracy: 'reported_exact' as const,
    })),
    accuracy: 'reported_exact',
  },
  accountUsageStatus: {
    state: 'fixture',
    accuracy: 'reported_exact',
    source: 'Synthetic account usage fixture',
    lastObservedAt: '2026-07-22T12:42:00Z',
    reason: null,
    requiredIntegration: 'Read-only App Server collection',
  },
  today: {
    input: 1_840_000,
    cachedInput: 404_800,
    output: 82_600,
    reasoningOutput: 31_400,
    total: 1_954_000,
    accuracy: 'reported_exact',
  },
  tokenStatus: {
    state: 'fixture',
    accuracy: 'reported_exact',
    source: 'Synthetic token-usage fixture',
    lastObservedAt: '2026-07-22T12:42:00Z',
    reason: null,
    requiredIntegration: 'Lifecycle hooks or OpenTelemetry',
  },
  turns: [
    {
      id: 'turn-fixture-003',
      threadId: 'thread-fixture-sol',
      project: 'local/example-project',
      model: 'gpt-5.4-sol',
      reasoningEffort: 'max',
      tokens: 1_954_000,
      durationMs: 10_860_000,
      accuracy: 'reported_exact',
    },
    {
      id: 'turn-fixture-002',
      threadId: 'thread-fixture-compact',
      project: 'local/example-project',
      model: 'gpt-5.4',
      reasoningEffort: 'high',
      tokens: 184_200,
      durationMs: 842_000,
      accuracy: 'reported_exact',
    },
  ],
  turnsStatus: {
    state: 'fixture',
    accuracy: 'reported_exact',
    source: 'Synthetic completed-turn fixture',
    lastObservedAt: '2026-07-22T12:42:00Z',
    reason: null,
    requiredIntegration: 'Lifecycle hooks or OpenTelemetry',
  },
  burn: {
    headline: 'High usage correlates with a large uncached context and extended reasoning.',
    factors: [
      '1.84 million reported input tokens',
      '22% cache reuse',
      'Sol model usage with Max reasoning configured',
      'four compactions and three subagent sessions',
    ],
    missingSignals: [
      {
        name: 'Exact quota units',
        source: 'Codex App Server',
        setupState: 'unsupported',
        detail: 'The installed interface reports percentages, not capacity units.',
      },
      {
        name: 'Direct project-level quota attribution',
        source: 'Codex App Server',
        setupState: 'unsupported',
        detail: 'Quota snapshots are account-scoped.',
      },
    ],
    method: 'Ranks observed signals; no causal claim is made.',
    confidence: 'medium',
    accuracy: 'estimated',
  },
  burnStatus: {
    state: 'fixture',
    accuracy: 'estimated',
    source: 'Synthetic local analysis fixture',
    lastObservedAt: '2026-07-22T12:42:00Z',
    reason: null,
    requiredIntegration: 'Token usage, completed turns, and quota snapshots',
  },
  channels: [
    {
      id: 'app-server',
      name: 'App Server',
      status: 'healthy',
      enabled: true,
      healthy: true,
      detail: 'Synthetic quota and account responses',
      lastEventAt: '2026-07-22T12:42:00Z',
      lastSuccessfulCollectionAt: '2026-07-22T12:42:00Z',
      latestError: null,
      capabilities: ['Quota windows', 'Account activity'],
      telemetryState: 'fixture',
      configurationStatus: 'Synthetic Demo source',
      restartCount: 0,
    },
    {
      id: 'lifecycle-hooks',
      name: 'Lifecycle hooks',
      status: 'healthy',
      enabled: true,
      healthy: true,
      detail: 'Synthetic turn completion fixture',
      lastEventAt: '2026-07-22T12:42:00Z',
      lastSuccessfulCollectionAt: '2026-07-22T12:42:00Z',
      latestError: null,
      capabilities: ['Turn completion', 'Model and reasoning', 'Attribution'],
      telemetryState: 'fixture',
      configurationStatus: 'Synthetic Demo source',
      restartCount: 0,
    },
    {
      id: 'opentelemetry',
      name: 'OpenTelemetry',
      status: 'healthy',
      enabled: true,
      healthy: true,
      detail: 'Synthetic token fixture',
      lastEventAt: '2026-07-22T12:42:00Z',
      lastSuccessfulCollectionAt: '2026-07-22T12:42:00Z',
      latestError: null,
      capabilities: ['Token composition', 'Usage Burn evidence'],
      telemetryState: 'fixture',
      configurationStatus: 'Synthetic Demo source',
      restartCount: 0,
    },
  ],
  modelStatus: {
    state: 'fixture',
    accuracy: 'reported_exact',
    source: 'Synthetic completed-turn fixture',
    lastObservedAt: '2026-07-22T12:42:00Z',
    reason: null,
    requiredIntegration: 'Lifecycle hooks or OpenTelemetry',
  },
  alerts: {
    active: [
      {
        id: 'fixture-warning',
        createdAt: fixtureObservedAt,
        collectionTimestamp: fixtureObservedAt,
        bucketId: 'codex:primary',
        bucketName: 'Codex 5 hour window',
        resetWindowId: 'fixture-primary-reset',
        resetsAt: fixtureResetAt,
        threshold: 75,
        usedPercent: 82,
        remainingPercent: 18,
        severity: 'warning',
        accuracy: 'reported_exact',
        dismissedAt: null,
        resolvedAt: null,
        unread: true,
        alertType: 'quota_threshold',
        alertSource: 'reported_quota',
        predictedExhaustionAt: isoOffset(108),
        forecastConfidence: 'medium',
      },
      {
        id: 'fixture-critical',
        createdAt: '2026-07-22T12:42:00Z',
        collectionTimestamp: '2026-07-22T12:42:00Z',
        bucketId: 'codex:critical',
        bucketName: 'Synthetic critical example',
        resetWindowId: 'fixture-critical-reset',
        resetsAt: '2026-07-27T00:00:00Z',
        threshold: 90,
        usedPercent: 93,
        remainingPercent: 7,
        severity: 'critical',
        accuracy: 'reported_exact',
        dismissedAt: null,
        resolvedAt: null,
        unread: true,
        alertType: 'quota_threshold',
        alertSource: 'reported_quota',
        predictedExhaustionAt: isoOffset(108),
        forecastConfidence: 'medium',
      },
    ],
    dismissed: [],
    history: [],
  },
  modelDistribution: [
    { label: 'gpt-5.4-sol', value: 88 },
    { label: 'gpt-5.4', value: 12 },
  ],
  reasoningDistribution: [
    { label: 'max', value: 84 },
    { label: 'high', value: 16 },
  ],
  warnings: [
    'Fixture/demo mode: values below are synthetic and do not describe your account.',
    'Project quota attribution is estimated because quota snapshots are account-level.',
  ],
};
