import type { Dashboard } from './types';

export const fixtureDashboard: Dashboard = {
  demoMode: true,
  collectorState: 'fixture data loaded',
  codexVersion: '0.144.1',
  lastEventAt: '2026-07-22T12:42:00Z',
  quota: [
    {
      id: 'codex:primary',
      name: 'Codex',
      windowLabel: '5 hour window',
      usedPercent: 82,
      remainingPercent: 18,
      resetsAt: '2026-07-22T15:00:00Z',
      accuracy: 'reported_exact',
    },
    {
      id: 'codex:secondary',
      name: 'Codex',
      windowLabel: 'Weekly window',
      usedPercent: 41,
      remainingPercent: 59,
      resetsAt: '2026-07-27T00:00:00Z',
      accuracy: 'reported_exact',
    },
  ],
  quotaStatus: {
    state: 'fixture',
    accuracy: 'reported_exact',
    source: 'Synthetic App Server fixture',
    lastObservedAt: '2026-07-22T12:42:00Z',
    reason: null,
    requiredIntegration: 'Read-only App Server collection',
  },
  accountUsage: {
    observedAt: '2026-07-22T12:42:00Z',
    lifetimeTokens: 25_480_000,
    peakDailyTokens: 3_420_000,
    longestRunningTurnSec: 10_860,
    currentStreakDays: 4,
    longestStreakDays: 11,
    dailyUsageBuckets: [
      {
        startDate: '2026-07-22',
        tokens: 2_138_200,
        observedAt: '2026-07-22T12:42:00Z',
        accuracy: 'reported_exact',
      },
    ],
    accuracy: 'reported_exact',
  },
  accountUsageStatus: {
    state: 'fixture',
    accuracy: 'reported_exact',
    source: 'Synthetic account usage fixture',
    lastObservedAt: '2026-07-22T12:42:00Z',
    reason: null,
    requiredIntegration: 'Read-only App Server collection',
  },
  today: {
    input: 1_840_000,
    cachedInput: 404_800,
    output: 82_600,
    reasoningOutput: 31_400,
    total: 1_954_000,
    accuracy: 'reported_exact',
  },
  tokenStatus: {
    state: 'fixture',
    accuracy: 'reported_exact',
    source: 'Synthetic token-usage fixture',
    lastObservedAt: '2026-07-22T12:42:00Z',
    reason: null,
    requiredIntegration: 'Lifecycle hooks or OpenTelemetry',
  },
  turns: [
    {
      id: 'turn-fixture-003',
      threadId: 'thread-fixture-sol',
      project: 'local/example-project',
      model: 'gpt-5.4-sol',
      reasoningEffort: 'max',
      tokens: 1_954_000,
      durationMs: 10_860_000,
      accuracy: 'reported_exact',
    },
    {
      id: 'turn-fixture-002',
      threadId: 'thread-fixture-compact',
      project: 'local/example-project',
      model: 'gpt-5.4',
      reasoningEffort: 'high',
      tokens: 184_200,
      durationMs: 842_000,
      accuracy: 'reported_exact',
    },
  ],
  turnsStatus: {
    state: 'fixture',
    accuracy: 'reported_exact',
    source: 'Synthetic completed-turn fixture',
    lastObservedAt: '2026-07-22T12:42:00Z',
    reason: null,
    requiredIntegration: 'Lifecycle hooks or OpenTelemetry',
  },
  burn: {
    headline: 'High usage correlates with a large uncached context and extended reasoning.',
    factors: [
      '1.84 million reported input tokens',
      '22% cache reuse',
      'Sol model usage with Max reasoning configured',
      'four compactions and three subagent sessions',
    ],
    missingSignals: [
      {
        name: 'Exact quota units',
        source: 'Codex App Server',
        setupState: 'unsupported',
        detail: 'The installed interface reports percentages, not capacity units.',
      },
      {
        name: 'Direct project-level quota attribution',
        source: 'Codex App Server',
        setupState: 'unsupported',
        detail: 'Quota snapshots are account-scoped.',
      },
    ],
    method: 'Ranks observed signals; no causal claim is made.',
    confidence: 'medium',
    accuracy: 'estimated',
  },
  burnStatus: {
    state: 'fixture',
    accuracy: 'estimated',
    source: 'Synthetic local analysis fixture',
    lastObservedAt: '2026-07-22T12:42:00Z',
    reason: null,
    requiredIntegration: 'Token usage, completed turns, and quota snapshots',
  },
  channels: [
    {
      id: 'app-server',
      name: 'App Server',
      status: 'healthy',
      enabled: true,
      healthy: true,
      detail: 'Synthetic quota and account responses',
      lastEventAt: '2026-07-22T12:42:00Z',
      lastSuccessfulCollectionAt: '2026-07-22T12:42:00Z',
      latestError: null,
      capabilities: ['Quota windows', 'Account activity'],
    },
    {
      id: 'lifecycle-hooks',
      name: 'Lifecycle hooks',
      status: 'healthy',
      enabled: true,
      healthy: true,
      detail: 'Synthetic turn completion fixture',
      lastEventAt: '2026-07-22T12:42:00Z',
      lastSuccessfulCollectionAt: '2026-07-22T12:42:00Z',
      latestError: null,
      capabilities: ['Turn completion', 'Model and reasoning', 'Attribution'],
    },
    {
      id: 'opentelemetry',
      name: 'OpenTelemetry',
      status: 'healthy',
      enabled: true,
      healthy: true,
      detail: 'Synthetic token fixture',
      lastEventAt: '2026-07-22T12:42:00Z',
      lastSuccessfulCollectionAt: '2026-07-22T12:42:00Z',
      latestError: null,
      capabilities: ['Token composition', 'Usage Burn evidence'],
    },
  ],
  modelStatus: {
    state: 'fixture',
    accuracy: 'reported_exact',
    source: 'Synthetic completed-turn fixture',
    lastObservedAt: '2026-07-22T12:42:00Z',
    reason: null,
    requiredIntegration: 'Lifecycle hooks or OpenTelemetry',
  },
  alerts: {
    active: [
      {
        id: 'fixture-warning',
        createdAt: '2026-07-22T12:42:00Z',
        collectionTimestamp: '2026-07-22T12:42:00Z',
        bucketId: 'codex:primary',
        bucketName: 'Codex 5 hour window',
        resetWindowId: 'fixture-primary-reset',
        resetsAt: '2026-07-22T15:00:00Z',
        threshold: 75,
        usedPercent: 82,
        remainingPercent: 18,
        severity: 'warning',
        accuracy: 'reported_exact',
        dismissedAt: null,
      },
      {
        id: 'fixture-critical',
        createdAt: '2026-07-22T12:42:00Z',
        collectionTimestamp: '2026-07-22T12:42:00Z',
        bucketId: 'codex:critical',
        bucketName: 'Synthetic critical example',
        resetWindowId: 'fixture-critical-reset',
        resetsAt: '2026-07-27T00:00:00Z',
        threshold: 90,
        usedPercent: 93,
        remainingPercent: 7,
        severity: 'critical',
        accuracy: 'reported_exact',
        dismissedAt: null,
      },
    ],
    dismissed: [],
    history: [],
  },
  modelDistribution: [
    { label: 'gpt-5.4-sol', value: 88 },
    { label: 'gpt-5.4', value: 12 },
  ],
  reasoningDistribution: [
    { label: 'max', value: 84 },
    { label: 'high', value: 16 },
  ],
  warnings: [
    'Fixture/demo mode: values below are synthetic and do not describe your account.',
    'Project quota attribution is estimated because quota snapshots are account-level.',
  ],
};
